[build-system]
requires = [
    "setuptools >= 42",
    "versioningit ~= 1.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.versioningit]

[tool.versioningit.write]
file = "src/skeleton/_version.py"
